### PR TITLE
Fix a couple minor bugs in the example

### PR DESCRIPTION
**Pull request by rswinkle**

### CODE REVIEW

**Comment by graphitemaster** [comment]
This is actually quite funny, not sure how I made that mistake. Nice catch.

**Comment by rswinkle** [comment]
Yeah, I noticed the incorrect compare several months ago but I was just browsing online at the time and I thought, "There's no way he made that mistake, I must be missing something".

Now I actually went to use it in something and it turned out I wasn't crazy.

I am curious why you don't make the the compare function a member for rb and avl?  It's going to be the same function for the life of the tree and is just extra typing every time you call those functions.  8 bytes of extra space in the tree is pretty insignificant.

**Comment by graphitemaster** [comment]
Faster comparisons really. If it were a member of the tree structure; that requires a dereference of the tree to load the pointer from the tree structure and then a dereference of the function pointer to place the call. The tree structure is mostly cold, it's only ever touched when reading from the root and when passing the aux stuff into the comparison where you sort of only pay for the aux cost if you use it. Having every comparison load from it an additional field to then immediately call is surely going to be slower than passing it around. I've not done any real performance tests to verify that but that was my rationale at the time. Looking at it I feel like the aux pointer thing too should've been passed by argument as well since it does have to look it up anyways

**Comment by rswinkle** [comment]
Fair enough.  That occurred to me but I think it's a worthwhile trade off for me and compare is only used in insert and search which access the tree immediately to get the root so the tree would be hot at that point and as you said it has to access the tree for aux anyway as it is now.

The only other thing I was going to change for what I'm using it for is having the insert functions return a node\* or NULL so you know if it already existed or not.  Having to call search first duplicates work.

I'm looking to replace [this](https://github.com/robwink/davinci/blob/master/darray.h) [mess](https://github.com/robwink/davinci/blob/master/darray.c) [at](https://github.com/robwink/davinci/blob/master/avl.h) [work](https://github.com/robwink/davinci/blob/master/avl.c) with your avl and and my CVector.  It's amazing how many ad-hoc manual vectors they had floating around that codebase.  I'm still finding/replacing them 6 months later.  It's an absolutely horrible codebase and as soon as I wrap up the last few reasonable things and publish an official release I'm gone and it'll go back to decaying unmaintained bit rot.  It's beyond saving.

So thank you for helping me clean up the code just a little bit more with your excellent, small, sane, and readable library.

**Comment by graphitemaster** [comment]
Looked at your CVector project. Another one of those vector implementations that I feel do it wrong. There is a much better way to do vectors in C that is type-safe while still allowing indexing of elements using the `[]` operator. I almost feel like writing a little library to showcase it so people would stop making these huge vector libraries in C

**Comment by rswinkle** [comment]
That's what the templates are for.  While I don't think it's a big deal to use the cvector_void for a one off occasionally, for anything that I use a lot or really care about speed I'd use a template, either generate it offline with the script or use the new macros.

I'm sure there are better C vector libraries out there but personally every one I've seen I consider worse than mine and fundamentally similar (except arguably less type safe and more annoying since they're constantly casting a void\* instead of just using byte\* for their generic vector)

**Comment by rswinkle** [comment]
And anything is better than Darray in davinci where it only stores void*'s.

**Comment by rswinkle** [comment]
Oh 2 things I forgot or should add/clarify.

I have seen Sean Barrett's [stretchy buffer](https://github.com/nothings/stb/blob/master/stretchy_buffer.h) concept which is different than all the other vector libraries I've seen and probably more what you're thinking of based on what you said.  I can appreciate it's simplicity but as he says it's an extremely leaky abstraction and compiler aliasing optimizations breaks it iirc and his last commit removes claims of C++ support probably for similar reasons.  I prefer the concrete nature of an actual struct/function style like mine which is more obvious and safer from a portability standpoint and allows easier modification and flexibility ala the constructors/destructors.

And in replacing Darray I would be using a template to generate a cvector_voidptr or something where voidptr is just a struct that wraps a void*.

Sorry to clutter up your inbox

**Comment by graphitemaster** [comment]
Did it because why not

https://github.com/graphitemaster/cvec

I prefer doing vectors in C like this

It's like Sean Barret's stretchy buffer, however it does not break under strict aliasing optimizations, since it uses a struct and does not attempt to poke integers willy nilly like his does. The abstraction is sort of leaky yes. Also it works in C++.

**Comment by rswinkle** [comment]
Interesting.  It is similar to stretchy_buffer as I expected though slightly more hybrid with an actual struct.  I have to go right now but I'll definitely look at it in more detail later.

Though I think the points in my previous post still apply to yours (ie harder to make arbitrary modifications, special cases etc.), it's definitely more of a middle ground and I'd rather work with yours than stb's.

**Pull request merged**
